name: Send Coverage Report To Codecov

on:
  # 当提交 main 分支的代码的时候触发 action
  push:
    branches:
      - master
  # 或对 main 分支进行 pull request 的时候
  pull_request:
    branches:
      - master

jobs:
  Send_Coverage_To_CodeCov:
    # 运行环境
    runs-on: ubuntu-latest
    steps:
      # 下载仓库源码
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      # 安装依赖 & 运行测试并生成覆盖率报告 & 项目打包
      - name: Install and Build
        run: |
          npm install
          npm run build:type
          npm run build
          npm run test

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
